#############################################################################
# Makefile for building: 3DSEncode
# Generated by qmake (2.01a) (Qt 4.7.4) on: sáb dez 17 22:36:19 2011
# Project:  3DSEncode.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile 3DSEncode.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Q3DSEncode.cpp \
		QEncodingDialog.cpp moc_Q3DSEncode.cpp \
		moc_QEncodingDialog.cpp \
		qrc_3DSEncode.cpp
OBJECTS       = main.o \
		Q3DSEncode.o \
		QEncodingDialog.o \
		moc_Q3DSEncode.o \
		moc_QEncodingDialog.o \
		qrc_3DSEncode.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		3DSEncode.pro
QMAKE_TARGET  = 3DSEncode
DESTDIR       = 
TARGET        = 3DSEncode

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Q3DSEncode.h ui_QEncodingDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 3DSEncode.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -o Makefile 3DSEncode.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile 3DSEncode.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/3DSEncode1.0.0 || $(MKDIR) .tmp/3DSEncode1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/3DSEncode1.0.0/ && $(COPY_FILE) --parents Q3DSEncode.h QEncodingDialog.h .tmp/3DSEncode1.0.0/ && $(COPY_FILE) --parents 3DSEncode.qrc .tmp/3DSEncode1.0.0/ && $(COPY_FILE) --parents main.cpp Q3DSEncode.cpp QEncodingDialog.cpp .tmp/3DSEncode1.0.0/ && $(COPY_FILE) --parents Q3DSEncode.ui QEncodingDialog.ui .tmp/3DSEncode1.0.0/ && $(COPY_FILE) --parents 3DSEncode_en.ts 3DSEncode_es.ts 3DSEncode_pt.ts 3DSEncode_fr.ts 3DSEncode_it.ts 3DSEncode_de.ts .tmp/3DSEncode1.0.0/ && (cd `dirname .tmp/3DSEncode1.0.0` && $(TAR) 3DSEncode1.0.0.tar 3DSEncode1.0.0 && $(COMPRESS) 3DSEncode1.0.0.tar) && $(MOVE) `dirname .tmp/3DSEncode1.0.0`/3DSEncode1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/3DSEncode1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Q3DSEncode.cpp moc_QEncodingDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Q3DSEncode.cpp moc_QEncodingDialog.cpp
moc_Q3DSEncode.cpp: Q3DSEncode.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Q3DSEncode.h -o moc_Q3DSEncode.cpp

moc_QEncodingDialog.cpp: QEncodingDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QEncodingDialog.h -o moc_QEncodingDialog.cpp

compiler_rcc_make_all: qrc_3DSEncode.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_3DSEncode.cpp
qrc_3DSEncode.cpp: 3DSEncode.qrc \
		images/help-about.png \
		images/3ds_icon.png \
		images/document-open.png \
		images/application-exit.png \
		images/video-x-generic.png \
		images/preferences-desktop-locale.png \
		images/document-save.png
	/usr/bin/rcc -name 3DSEncode 3DSEncode.qrc -o qrc_3DSEncode.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Q3DSEncode.h ui_QEncodingDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Q3DSEncode.h ui_QEncodingDialog.h
ui_Q3DSEncode.h: Q3DSEncode.ui
	/usr/bin/uic Q3DSEncode.ui -o ui_Q3DSEncode.h

ui_QEncodingDialog.h: QEncodingDialog.ui
	/usr/bin/uic QEncodingDialog.ui -o ui_QEncodingDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Q3DSEncode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Q3DSEncode.o: Q3DSEncode.cpp Q3DSEncode.h \
		ui_Q3DSEncode.h \
		QEncodingDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Q3DSEncode.o Q3DSEncode.cpp

QEncodingDialog.o: QEncodingDialog.cpp QEncodingDialog.h \
		ui_QEncodingDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QEncodingDialog.o QEncodingDialog.cpp

moc_Q3DSEncode.o: moc_Q3DSEncode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Q3DSEncode.o moc_Q3DSEncode.cpp

moc_QEncodingDialog.o: moc_QEncodingDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QEncodingDialog.o moc_QEncodingDialog.cpp

qrc_3DSEncode.o: qrc_3DSEncode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_3DSEncode.o qrc_3DSEncode.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

